// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvhfaahqlmyggsgiwplk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2aGZhYWhxbG15Z2dzZ2l3cGxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTA3NzcsImV4cCI6MjA3MzgyNjc3N30.Waj3yo20UcvyTepw1qTnyIoGRXh4t5NNr2CaimrqD6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});